export const Types = {
  GET_WALLET: "GET_WALLET",
  SET_ETH: "SET_ETH",
  SELECT_WALLET_TYPE: "SELECT_WALLET_TYPE",
  SET_PXA: "SRT_PXA",
  SET_PROVIDER: "SET_PROVIDER",
  ERROR_MESSAGE: "ERROR_MESSAGE",
  GET_ETH_MULTISEND: "GET_ETH_MULTISEND",
  GET_LINE_GRAPH: "GET_LINE_GRAPH",
  GET_WATCHER: "GET_WATCHER",
  GET_VESTING_DETAILS: "GET_VESTING_DETAILS",

  GET_LIQUIDITY_INFO: "GET_LIQUIDITY_INFO",
  GET_USER_INFO_DETAILS: "ET_USER_INFO_DETAILS",

  GET_POOL_INFO: "GET_POOL_INFO",

  GET_ACTIVE_PAIRS: "GET_ACTIVE_PAIRS",
  GET_FINISHED_PAIRS: "GET_FINISHED_PAIRS",
  GET_VOTES: "GET_VOTES",

  GET_SWAP_REWARDS: "GET_SWAP_REWARDS",

  GET_FAUCET_REWARDS: "GET_FAUCET_REWARDS",
};
